### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by andrevenancio** [nature-of-code/noc-syllabus-S21#1]
Bless Github to show us some updates. This course seems great. How do I sign in? Can it be done remotely?

**Comment by shiffman** [comment]
Hi @andrevenancio! The resources here will be open and you are welcome to follow along this syllabus. The class itself, however, is for registered NYU students only. I will be covering some additional examples also in live streams on YouTube:  https://www.youtube.com/thecodingtrain.
